# Generated by Django 4.2 on 2023-04-17 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0001_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='friend.friends')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='match.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
