# Generated by Django 4.2 on 2023-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_initial'),
        ('match_details', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetails',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='match_details', to='friend.friends'),
        ),
    ]
