# Generated by Django 4.2 on 2023-04-17 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stadium', models.CharField(max_length=150)),
                ('club_image', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='match.match')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='match.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
