# Generated by Django 4.2 on 2023-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('competition', models.CharField(max_length=50)),
                ('home_lineup', models.TextField(max_length=300)),
                ('away_lineup', models.TextField(max_length=300)),
                ('goalscorers', models.CharField(max_length=50)),
                ('assists', models.TextField(max_length=200)),
                ('yellow_cards', models.TextField(max_length=200)),
            ],
        ),
    ]
