# Generated by Django 4.2 on 2023-04-19 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('friend', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('competition', models.CharField(max_length=50)),
                ('home_lineup', models.TextField(blank=True, max_length=300, null=True)),
                ('away_lineup', models.TextField(blank=True, max_length=300, null=True)),
                ('goalscorers', models.CharField(blank=True, max_length=50, null=True)),
                ('assists', models.TextField(blank=True, max_length=200, null=True)),
                ('yellow_cards', models.TextField(blank=True, max_length=200, null=True)),
                ('photos', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='club.club')),
                ('friends', models.ManyToManyField(blank=True, related_name='match_details', to='friend.friends')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='club.club')),
            ],
        ),
    ]
