# Generated by Django 4.2 on 2023-04-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('competition', models.CharField(max_length=50)),
                ('home_lineup', models.TextField(max_length=300)),
                ('away_lineup', models.TextField(max_length=300)),
                ('goalscorers', models.CharField(max_length=50)),
                ('assists', models.TextField(max_length=200)),
                ('yellow_cards', models.TextField(max_length=200)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='club.club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='club.club')),
            ],
        ),
    ]
