# Generated by Django 4.2 on 2023-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_remove_match_away_lineup_remove_match_home_lineup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
