# Generated by Django 4.2 on 2023-04-20 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0004_alter_match_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='match', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
