# Generated by Django 4.2 on 2023-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_rename_user_match_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='beer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ground_rating',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
